name: "web_app"
mode: "dev"
port: 8081
version: "v0.0.1"
startTime: "2022-03-02"
machineId: 1

auth:
  jwt_expire: 8760

log:
  level: "debug"
  filename: "web_app.log"
  max_size: 200
  max_age: 30
  max_backups: 7

mysql:
  host: "219.228.135.107"
  port: 3306
  user: "root"
  password: "Mysql:12138"
  dbname: "bluebell"
  max_open_conns: 200
  max_idle_conns: 50

redis:
  host: "219.228.135.107"
  port: 6379
  db: 0
  password: ""
  pool_size: 100
  min_idle_conns: 5
